[package]
name = "s42_starknet_workshop"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]

[dev-dependencies]
cairo_test = "2.8.4"
assert_macros = "2.8.5"

[cairo]
enable-gas = false

